export const SECTION_NAMES = {
  what_is_a_computer_intro: "🌟 Getting Oriented",
  hardware: "🔩 Hardware & Physical Layer",
  firmware: "🔥 Firmware & Boot",
  os: "🖥️ Operating Systems",
  cli: "⌨️ Command Line",
  networking: "🌐 Networking & Internet",
  software: "📦 Software Concepts",
  history: "📜 History",
  physics: "⚡ Physics & Materials",
  core: "🧩 Core Programming Concepts",
  languages: "🗣️ The Language Landscape",
  data_structures: "📦 Basic Data Structures",
  data: "🗂️ Working With Data",
  oop: "🏗️ Object-Oriented Basics",
  functional: "λ Functional Basics",
  git: "🌿 Version Control",
  reading_code: "🔍 Reading Real Code",
  ai: "🤖 AI: History, Theory & How It Works",
  ai_advanced: "🧠 AI: Going Deeper",
  mechanics: "⚙️ Deeper Language Mechanics",
  data_structures_advanced: "🌲 Advanced Data Structures",
  algorithms_advanced: "🧮 Advanced Algorithms",
  architecture: "🏛️ Software Architecture",
  databases: "🗄️ Databases",
  web: "🌐 Web Fundamentals",
  concurrency: "🔀 Concurrency",
  hardware_callback: "🔗 Hardware Callback",
  ai_building: "🤖 AI: Building With It",
  patterns: "🧵 Design Patterns",
  systems: "🏙️ Systems Design",
  security: "🛡️ Security Fundamentals",
  performance: "⚡ Performance & Optimization",
  devops: "🚀 DevOps & Cloud",
  advanced_ai: "🔮 Advanced AI",
  distributed: "🌍 Distributed Systems",
  ai_deep: "🧠 The Modern AI Stack",
  theory_of_computation: "🧭 Theory of Computation",
  capstone: "🏆 Capstone & Beyond",
};
